### ISSUE TITLE
Response signature doesnt match the calculated signature

### ISSUE THREAD

**Issue by Ravenglass** [bankofmaldives/bml-connect#3]
The response signature doesnt match the calculated signature. Probably the return signature isnt calculated using the same method.

This issue only happens in the Production Environment and works fine in the Test Environment.

The following signature was calculated using sha1 and accepted by the gateway during the creation of the transaction.
**Generated Signature:** de9b227caed988707feeebf52e72782debd00c72

The following signature was recieved once the same transaction was completed.
**Response Signature:** XgI/owet/4nl1S0cmmFo3A==

**Comment by sverraest** [comment]
Hi @Ravenglass 

Thank you for raising this issue. Could you also send us the transaction ID to developers@pomelopay.com and we will be able to assist further.

**Comment by sverraest** [comment]
Hi there @Ravenglass 
Would it be possible to re-test this with a new transaction and let us know the outcome?

**Comment by akhilmanu007** [comment]
hai @Ravenglass  
can you share the webhook handler  you used here for reference ?

**Comment by Ravenglass** [comment]
@sverraest sorry about the late response. Must have missed this. We were able to re-test and get the correct signature. Thanx. 

@akhilmanu007, not sure what you mean. The webhook URL can be set in the merchant portal and can be pretty much anything as long as its https. The webhook URL will recieve the Signature along with the Transaction ID. So you can calculate the signature and see if the recieved one matches the calculated one.

**Comment by akhilmanu007** [comment]
@Ravenglass  can u share any documentation for handling the webhook  response ?
it would be great help..

**Comment by Ravenglass** [comment]
@akhilmanu007 The documentation is here > https://github.com/bankofmaldives/bml-connect#webhooks

**Comment by akhilmanu007** [comment]
@Ravenglass @sverraest  Actually what i want to do is how to catch/received the webhook response in my aspx page?
