### ISSUE TITLE
"Error creating transaction" - 500

### ISSUE THREAD

**Issue by dinuth-perera** [bankofmaldives/bml-connect#9]
I'm developing add-on for Odoo 14. 
language : python

Process:
 1. User Can select BML Connect from the Odoo website while making payment.
 2. After that , it will redirect to merchant site for payment ( POST all related data )
 
when redirected to payment it's response "Error creating transaction".

![Screenshot from 2021-12-03 04-18-24](https://user-images.githubusercontent.com/63660913/144516446-9c74bd0b-4b53-46a0-8ae9-5cce76ad0438.png)

**Comment by lapzone** [comment]
problem with currency because BML gave a testing account which is USD please change the currency to MVR it will work
